services:
  - type: web
    name: ipfs-music-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://www.nyauwu.com
