global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway-proxy'
    static_configs:
      - targets: ['gateway-proxy:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'ipfs-node'
    static_configs:
      - targets: ['ipfs-node:5001']
    metrics_path: '/debug/metrics/prometheus'
    scrape_interval: 60s
